# Site settings
title: Sapir Ezra
description: Software Engineering Student
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sapir Ezra
user_description: I'm a Software Engineering student with natural curiosity, always searching for the next thing to learn. The field that I chose to specialize in is <b>data science</b>. I am completed a Machine Learning course on Coursera. You can take a look at my projects at my GitHub linked above.
user_title: Software Engineering Student
email: sapire88@gmail.com
# twitter_username: lorem_ipsum
# github_username:  sapire
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
